<a href="https://colab.research.google.com/github/R0berth456/-Tarea-11-Ejercicios-Unidad-04-D-Gauss-Jacobi-y-Gauss-Seidel/blob/main/%5BTarea_11%5D_Ejercicios_Unidad_04_D_%7C_Gauss_Jacobi_y_Gauss_Seidel.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Primer Literal

In [1]:
import numpy as np

def gauss_jacobi(
    A: np.array, b: np.array, x0: np.array, tol: float, max_iter: int
) -> np.array:
    # --- Validación de los argumentos de la función ---
    if not isinstance(A, np.ndarray):
        A = np.array(A, dtype=float)
    assert A.shape[0] == A.shape[1], "La matriz A debe ser de tamaño n-by-(n)."

    if not isinstance(b, np.ndarray):
        b = np.array(b, dtype=float)
    assert b.shape[0] == A.shape[0], "El vector b debe ser de tamaño n."

    if not isinstance(x0, np.ndarray):
        x0 = np.array(x0, dtype=float)
    assert x0.shape[0] == A.shape[0], "El vector x0 debe ser de tamaño n."

    # --- Algoritmo ---
    n = A.shape[0]
    x = x0.copy()
    for k in range(1, max_iter):
        x_new = np.zeros((n, 1))  # prealloc
        for i in range(n):
            suma = sum([A[i, j] * x[j] for j in range(n) if j != i])
            x_new[i] = (b[i] - suma) / A[i, i]

        if np.linalg.norm(x_new - x) < tol:
            return x_new

        x = x_new.copy()

    return x

a)

In [2]:
A = [
    [3, -1, 1],
    [3, 6, 2],
    [3, 3, 7]
]

b = [1, 0, 4]

x = gauss_jacobi(A, b, [0, 0, 0], 10e-5, 100)
print(x)


[[ 0.0350863 ]
 [-0.23685698]
 [ 0.65787809]]


b)

In [3]:
A = [
    [10, -1, 1],
    [-1, 10, -2],
    [0, -2, 10]
]

b = [9, 7, 6]

x = gauss_jacobi(A, b, [0, 0, 0], 10e-5, 100)
print(x)

[[0.9159701]
 [0.9495603]
 [0.7899054]]


c)

In [4]:
A = [
    [10, 5, 0, 0],
    [5, 10, -4, 0],
    [0, -4, -8, 1],
    [0, 0, -1, 5]
]

b = [6, 25, -11, -11]

x = gauss_jacobi(A, b, [0, 0, 0, 0], 10e-5, 100)
print(x)

[[-0.78792172]
 [ 2.77583088]
 [-0.29530611]
 [-2.25906474]]


d)

In [5]:
A = [
    [4, 1, 1, 0, 1],
    [-1, -3, 1, 1, 0],
    [2, 1, 5, -1, -1],
    [-1, -1, -1, 4, 0],
    [0, 2, -1, 1, 4]
]

b = [6, 6, 6, 6, 6]

x = gauss_jacobi(A, b, [0, 0, 0, 0, 0], 10e-5, 100)
print(x)

[[ 0.78661584]
 [-1.00257369]
 [ 1.86634212]
 [ 1.91259293]
 [ 1.98974776]]


Segundo Literal

In [6]:
def gauss_seidel(
    A: np.array, b: np.array, x0: np.array, tol: float, max_iter: int
) -> np.array:
    # --- Validación de los argumentos de la función ---
    if not isinstance(A, np.ndarray):
        A = np.array(A, dtype=float)
    assert A.shape[0] == A.shape[1], "La matriz A debe ser de tamaño n-by-(n)."

    if not isinstance(b, np.ndarray):
        b = np.array(b, dtype=float)
    assert b.shape[0] == A.shape[0], "El vector b debe ser de tamaño n."

    if not isinstance(x0, np.ndarray):
        x0 = np.array(x0, dtype=float)
    assert x0.shape[0] == A.shape[0], "El vector x0 debe ser de tamaño n."

    # --- Algoritmo ---
    n = A.shape[0]
    x = x0.copy()

    for k in range(1, max_iter):
        x_new = np.zeros((n, 1))  # prealloc
        for i in range(n):
            suma = sum([A[i, j] * x_new[j] for j in range(i) if j != i]) + sum(
                [A[i, j] * x[j] for j in range(i, n) if j != i]
            )
            x_new[i] = (b[i] - suma) / A[i, i]

        if np.linalg.norm(x_new - x) < tol:
            return x_new

        x = x_new.copy()

    return x

a)

In [7]:
A = [
    [3, -1, 1],
    [3, 6, 2],
    [3, 3, 7]
]

b = [1, 0, 4]

x = gauss_seidel(A, b, [0, 0, 0], 10e-5, 100)
print(x)


[[ 0.03510326]
 [-0.23683891]
 [ 0.6578867 ]]


b)

In [8]:

A = [
    [10, -1, 1],
    [-1, 10, -2],
    [0, -2, 10]
]

b = [9, 7, 6]

x = gauss_seidel(A, b, [0, 0, 0], 10e-5, 100)
print(x)


[[0.91596497]
 [0.94957898]
 [0.7899158 ]]


c)

In [9]:
A = [
    [10, 5, 0, 0],
    [5, 10, -4, 0],
    [0, -4, -8, 1],
    [0, 0, -1, 5]
]

b = [6, 25, -11, -11]

x = gauss_seidel(A, b, [0, 0, 0, 0], 10e-5, 100)
print(x)


[[-0.78791707]
 [ 2.77583885]
 [-0.29530191]
 [-2.25906038]]


d)

In [10]:
A = [
    [4, 1, 1, 0, 1],
    [-1, -3, 1, 1, 0],
    [2, 1, 5, -1, -1],
    [-1, -1, -1, 4, 0],
    [0, 2, -1, 1, 4]
]

b = [6, 6, 6, 6, 6]

x = gauss_seidel(A, b, [0, 0, 0, 0, 0], 10e-5, 100)
print(x)

[[ 0.78663577]
 [-1.00257108]
 [ 1.86632614]
 [ 1.91259771]
 [ 1.98971765]]


Tercer Literal

a)

In [11]:
A = [
    [3, -1, 1],
    [3, 6, 2],
    [3, 3, 7]
]

b = [1, 0, 4]

x = gauss_jacobi(A, b, [0, 0, 0], 10e-3, 100)
print(x)

[[ 0.03516089]
 [-0.23570619]
 [ 0.65922185]]


b)

In [13]:
A = [
    [10, -1, 1],
    [-1, 10, -2],
    [0, -2, 10]
]

b = [9, 7, 6]

x = gauss_jacobi(A, b, [0, 0, 0], 10e-3, 100)
print(x)

[[0.91603]
 [0.94913]
 [0.78962]]


c)

In [14]:
A = [
    [10, 5, 0, 0],
    [5, 10, -4, 0],
    [0, -4, -8, 1],
    [0, 0, -1, 5]
]

b = [6, 25, -11, -11]

x = gauss_jacobi(A, b, [0, 0, 0, 0], 10e-3, 100)
print(x)


[[-0.788375  ]
 [ 2.77715625]
 [-0.29553125]
 [-2.26032813]]


d)

In [15]:
A = [
    [4, 1, 1, 0, 1],
    [-1, -3, 1, 1, 0],
    [2, 1, 5, -1, -1],
    [-1, -1, -1, 4, 0],
    [0, 2, -1, 1, 4]
]

b = [6, 6, 6, 6, 6]

x = gauss_jacobi(A, b, [0, 0, 0, 0, 0], 10e-3, 100)
print(x)

[[ 0.78718101]
 [-1.00174151]
 [ 1.8658388 ]
 [ 1.91274157]
 [ 1.98672138]]


Cuarto Literal

a)

In [16]:
A = [
    [3, -1, 1],
    [3, 6, 2],
    [3, 3, 7]
]

b = [1, 0, 4]

x = gauss_seidel(A, b, [0, 0, 0], 10e-3, 100)
print(x)

[[ 0.0361492 ]
 [-0.23660752]
 [ 0.65733928]]


b)

In [17]:
A = [
    [10, -1, 1],
    [-1, 10, -2],
    [0, -2, 10]
]

b = [9, 7, 6]

x = gauss_seidel(A, b, [0, 0, 0], 10e-3, 100)
print(x)


[[0.91593697]
 [0.94956218]
 [0.78991244]]


c)

In [19]:
A = [
    [10, 5, 0, 0],
    [5, 10, -4, 0],
    [0, -4, -8, 1],
    [0, 0, -1, 5]
]

b = [6, 25, -11, -11]

x = gauss_seidel(A, b, [0, 0, 0, 0], 10e-3, 100)
print(x)

[[-0.78802812]
 [ 2.77579328]
 [-0.29528544]
 [-2.25905709]]


d)

In [20]:
A = [
    [4, 1, 1, 0, 1],
    [-1, -3, 1, 1, 0],
    [2, 1, 5, -1, -1],
    [-1, -1, -1, 4, 0],
    [0, 2, -1, 1, 4]
]

b = [6, 6, 6, 6, 6]

x = gauss_seidel(A, b, [0, 0, 0, 0, 0], 10e-3, 100)
print(x)

[[ 0.78616258]
 [-1.00240703]
 [ 1.86606999]
 [ 1.91245638]
 [ 1.98960692]]


Quinto Literal

a)

In [30]:
A = [
    [2, -1, 1],
    [2, 2, 2],
    [-1, -1, 2]
]

b = [-1, 4, -5]

x = gauss_jacobi(A, b, [0, 0, 0], 10e-5, 25)
print(x)


[[ -7.73114914]
 [-32.92459655]
 [  7.73114914]]


b)

In [22]:
A = [
    [2, -1, 1],
    [2, 2, 2],
    [-1, -1, 2]
]

b = [-1, 4, -5]

x = gauss_seidel(A, b, [0, 0, 0], 10e-5, 25)
print(x)


[[ 0.99998474]
 [ 2.00001717]
 [-0.99999905]]


Sexto Literal

b)

In [27]:
A = [
    [1, 0, -1],
    [-0.5, 1, -0.25],
    [1, -0.5, 1]
]

b = [0.2, -1.425, 2]

x = gauss_seidel(A, b, [0, 0, 0], 10e-22, 300)
print(x)
print()
y = gauss_jacobi(A, b, [0, 0, 0], 10e-22, 300)
print(y)

[[ 0.9]
 [-0.8]
 [ 0.7]]

[[ 0.89979164]
 [-0.80015806]
 [ 0.70025541]]


c)

In [31]:
A = [
    [1, 0, -2],
    [-0.5, 1, -0.25],
    [1, -0.5, 1]
]

b = [0.2, -1.425, 2]

x = gauss_seidel(A, b, [0, 0, 0], 10e-22, 300)
print(x)
print()
y = gauss_jacobi(A, b, [0, 0, 0], 10e-22, 300)
print(y)

[[-1.56863478e+41]
 [-9.80396739e+40]
 [ 1.07843641e+41]]

[[-1.79225360e+43]
 [-4.51500391e+42]
 [ 6.72394565e+42]]


Octavo Literal

b)

In [37]:
A = [
   [4, -1, 0, 0, -1, 0, 0, 0, 0, 0, 0, 0],
   [-1, 4, .1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
   [0, -1, 4, -1, 0, 0, 0, 0, 0, 0, 0, 0],
   [0, 0, -1, 4, 0, -1, 0, 0, 0, 0, 0, 0],
   [-1, 0, 0, 0, 4, 0, -1, 0, 0, 0, 0, 0],
   [0, 0, 0, -1, 0, 4, 0, -1, 0, 0, 0, 0],
   [0, 0, 0, 0, -1, 0, 4, 0, -1, 0, 0, 0],
   [0, 0, 0, 0, 0, -1, 0, 4, 0, 0, 0, -1],
   [0, 0, 0, 0, 0, 0, -1, 0, 4, -1, 0, 0],
   [0, 0, 0, 0, 0, 0, 0, 0, -1, 4, -1, 0],
   [0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 4, -1],
   [0, 0, 0, 0, 0, -1, 0, 0, 0, 0, -1, 4]
]

b = [220, 110, 110, 220, 110, 110, 110, 110, 220, 110, 110, 220]

x = gauss_jacobi(A, b, [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 10, 250)
print(x)

[[81.59873047]
 [46.05927734]
 [59.57724609]
 [84.89550781]
 [62.87402344]
 [63.58300781]
 [63.58300781]
 [63.70117188]
 [85.72265625]
 [63.70117188]
 [63.70117188]
 [85.72265625]]


c)

In [36]:
A = [
   [4, -1, 0, 0, -1, 0, 0, 0, 0, 0, 0, 0],
   [-1, 4, .1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
   [0, -1, 4, -1, 0, 0, 0, 0, 0, 0, 0, 0],
   [0, 0, -1, 4, 0, -1, 0, 0, 0, 0, 0, 0],
   [-1, 0, 0, 0, 4, 0, -1, 0, 0, 0, 0, 0],
   [0, 0, 0, -1, 0, 4, 0, -1, 0, 0, 0, 0],
   [0, 0, 0, 0, -1, 0, 4, 0, -1, 0, 0, 0],
   [0, 0, 0, 0, 0, -1, 0, 4, 0, 0, 0, -1],
   [0, 0, 0, 0, 0, 0, -1, 0, 4, -1, 0, 0],
   [0, 0, 0, 0, 0, 0, 0, 0, -1, 4, -1, 0],
   [0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 4, -1],
   [0, 0, 0, 0, 0, -1, 0, 0, 0, 0, -1, 4]
]

b = [220, 110, 110, 220, 110, 110, 110, 110, 220, 110, 110, 220]

x = gauss_seidel(A, b, [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 10, 250)
print(x)

[[82.04627686]
 [46.53746918]
 [60.13291847]
 [85.94719503]
 [63.77875061]
 [65.11658196]
 [64.70993881]
 [65.5444085 ]
 [87.1606638 ]
 [65.43725257]
 [65.62457615]
 [87.68528953]]
